### ISSUE TITLE
Crashes when using with RxSwift/RxCocoa

### ISSUE THREAD

**Issue by icanzilb** [JohnSundell/TestDrive#6]
```
marin:Developer marin$ testdrive RxSwift RxCocoa
🕵️‍♀️  Finding pod 'RxSwift'...
📦  Cloning https://github.com/reactivex/rxswift.git...
🚢  Resolving latest version...
📋  Checking out version 3.4.0...
🚗  Rx is ready for test drive

🕵️‍♀️  Finding pod 'RxCocoa'...
📦  Cloning https://github.com/reactivex/rxswift.git...

💥  ShellOutError(message: "fatal: destination path \'rxswift\' already exists and is not an empty directory.", output: "")
```

**Comment by icanzilb** [comment]
This is probably because `RxSwift` and `RxCocoa` are located in the same repo. Maybe you need to generate unique folder names when cloning locally? or re-use the existing folder (even better?)

**Comment by JohnSundell** [comment]
Great find @icanzilb! 👍 Fixed in https://github.com/JohnSundell/TestDrive/commit/a83e5bd700a2a74a4db581e97eecb94c7d8be5ed ✅ 

Since both RxSwift & RxCocoa are in the same repository, you actually only need to pass one of them to Test Drive, but it still shouldn't crash when you pass both of them.

Let me know if the fix works for you, I just tried test driving both RxSwift + RxCocoa and it works for me here.

Now pack to reading my RxSwift book 😉

**Comment by JohnSundell** [comment]
I should also note that once the playground opens, you'll need to select the scheme for RxSwift, build that, then do the same for RxCocoa - before you can use them. I want to automate that process in an upcoming version of Test Drive, pre-build all schemes or something like that.

**Comment by JohnSundell** [comment]
@icanzilb can this be closed? 😇

**Comment by icanzilb** [comment]
I thought I did close it earlier today (I wonder wich issue I did close) ...
